# Generated by Django 3.2.8 on 2021-10-28 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('rate', models.DecimalField(decimal_places=10, max_digits=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_cat', models.CharField(max_length=100)),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Hotels.price')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=200)),
                ('slug', models.SlugField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Hotels.room', unique=True)),
            ],
        ),
    ]
