# Generated by Django 3.2.8 on 2021-10-28 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotels.room'),
        ),
    ]
