# Generated by Django 3.2.8 on 2021-10-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0002_auto_20211028_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hotels.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='Start and end in San Francisco! With the in-depth cultural tour Northern California Summer 2019, you have a 8 day tour package taking you through San Francisco, USA and 9 other destinations in USA. Northern California Summer 2019 includes accommodation as well as an expert guide, meals, transport and more.', max_length=200),
        ),
    ]
