# Generated by Django 3.2.8 on 2021-10-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0003_auto_20211028_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='Start and end in San Francisco! With the in-depth cultural .', max_length=200),
        ),
    ]
