# Generated by Django 3.2.8 on 2021-10-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotels', '0005_auto_20211028_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
